# @package _group_
experiment: default
pg_methods:
  - dpg
  - ipw
  - dr-d
  - dr-k
n_runs: 10
n_rounds_train: 1000
n_rounds_test: 100000
dim_context: 5
reward_function: quadratic
behavior_policy_function: linear
reward_noise: 4
action_noise: 4
min_action: -10.0
max_action: 10.0
n_jobs: 12
random_state: 12345
